development:
  dialect: mysql
  datasource: root:password@tcp(localhost:3306)/gin_demo?charset=utf8mb4&parseTime=True&loc=Local
  dir: db/migrations
  table: migrations

test:
  dialect: mysql
  datasource: root:password@tcp(localhost:3306)/gin_demo_test?charset=utf8mb4&parseTime=True&loc=Local
  dir: db/migrations
  table: migrations

production:
  dialect: mysql
  datasource: $DATABASE_URL
  dir: db/migrations
  table: migrations
